### ISSUE TITLE
Sample address is not hex

### ISSUE THREAD

**Issue by jeremyjams** [iExecBlockchainComputing/documentation-tools#17]
In https://tools.docs.iex.ec/tools/web3mail/methods/fetchmycontacts, address is not hex :slightly_smiling_face: 
```
        address: '0x9pCf798816D4b9b9866b5330EEa46a183ishy780'
    }    
]
```

**Comment by jeremyjams** [comment]
@PierreJeanjacquot

**Comment by abbesBenayache** [comment]
Hi @jeremyjams ,
thanks for pointing out the issue. I've fixed it by updating the addresses to proper hexadecimal format in the `fetchMyContacts` method.

**Comment by jeremyjams** [comment]
Thanks @abbesBenayache :slightly_smiling_face: :+1:
